// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function TakeScreenshot(arg1:number,arg2:number,arg3:number,arg4:number):Promise<string>;
