// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function TakeScreenshot(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TakeScreenshot'](arg1, arg2, arg3, arg4);
}
